### ISSUE TITLE
Set Attendance Sequence Diagram

### ISSUE THREAD

**Issue by weidak** [weidak/pe#17] opened 2021-11-12 09:40 UTC
The words on the sequence diagram is too small to read. This could be divided into smaller Reference Frames instead and not overwhelm readers.

![image.png](https://raw.githubusercontent.com/weidak/pe/main/files/d075f7df-f8c2-4ff1-a792-b1f9665ebdde.png)

**Comment by nus-se-script** [comment] 2021-11-16 18:32
# Team's Response
Same diagram with additional details.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Delete Attendance sequence diagram page 22
>
>**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
>The sequence diagram is too small for normal readers to read. Reference Diagrams should be used here instead to make the interactions clearer.
>
>
>![image.png](https://raw.githubusercontent.com/nus-cs2113-AY2122S1/pe/master/files/5f5184e0-2770-4bb6-99f0-e09a41544d29.png)
>
>
>
>
>
>
><hr>
><sub>[original: nus-cs2113-AY2122S1/pe-interim#1783] [original labels: severity.High type.DocumentationBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>There exists a zoom function. Also, the flaw is purely cosmetic (font issues). Severity should be 'VeryLow'.


# Items for the Tester to Verify
## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)





- [x] I disagree

**Reason for disagreement:** This diagram is different from the other diagram that it was marked as a duplicate. As this could have been done by a different person, this is the same issue but executed on a different diagram.

-------------------
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.High`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------

**Closed as completed** 2022-11-06 05:35 UTC
Labels: type.DocumentationBug, severity.High, status.Done
