### ISSUE TITLE
Object Diagrams associations are invalid

### ISSUE THREAD

**Issue by weidak** [weidak/pe#14] opened 2021-11-12 09:36 UTC
Moreover, they added the arrowheads which are inaccurate as well.

![image.png](https://raw.githubusercontent.com/weidak/pe/main/files/bbff40a3-cd62-404f-953b-52cb9c180e67.png)

**Comment by nus-pe-script** [comment] 2021-11-16 18:32
# Team's Response
Diagram is a copy with additional details. Cascading mistake.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Names of object diagrams should be underlined and have a colon preceding it
>
>**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
>Names of object diagrams should be underlined and have a colon preceding it
>
>![image.png](https://raw.githubusercontent.com/nus-cs2113-AY2122S1/pe/master/files/03916c4b-eba4-4b84-8dfb-69f9bb2efe0b.png)
>
>
>
>
>
>
><hr>
><sub>[original: nus-cs2113-AY2122S1/pe-interim#807] [original labels: severity.Medium type.DocumentationBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>Text formatting/font related.


# Items for the Tester to Verify
## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)



- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.High`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------

**Closed as completed** 2022-11-06 05:35 UTC
Labels: type.DocumentationBug, severity.High, status.Done
