### ISSUE TITLE
Wrong use of Alt blocks in Set Mark Seq Diagram

### ISSUE THREAD

**Issue by weidak** [weidak/pe#20] opened 2021-11-12 09:45 UTC
They should be Opt blocks instead

![image.png](https://raw.githubusercontent.com/weidak/pe/main/files/395394ef-8833-49ee-a4d2-bb2fede070a5.png)

**Comment by nus-pe-script** [comment] 2021-11-16 18:32
# Team's Response
Diagram is inherited with additional details/minor changes. Cascading mistake.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Wrong use of "alt"
>
>**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
>The notation `opt` should be used instead since it only has 1 option.
>
>![image.png](https://raw.githubusercontent.com/nus-cs2113-AY2122S1/pe/master/files/d0d61481-4211-4958-934e-2c4bee96a4ae.png)
>
>
>
>
>
>
><hr>
><sub>[original: nus-cs2113-AY2122S1/pe-interim#206] [original labels: severity.VeryLow type.DocumentationBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>typo error


# Items for the Tester to Verify
## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)







- [x] I disagree

**Reason for disagreement:** As they are different diagrams but of the same bug, I believe they can be separated as the diagrams could have been done by different individuals.

-------------------
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.High`]

- [x] I disagree

**Reason for disagreement:** I think this should be of severity.Low instead, as it could be misleading to users that there is another condition that was omitted during the making of the diagram.

-------------------

**Closed as completed** 2022-11-06 05:35 UTC
Labels: type.DocumentationBug, severity.High, status.Done
