### ISSUE TITLE
Add Student Sequence Diagram Method Missing

### ISSUE THREAD

**Issue by weidak** [weidak/pe#11] opened 2021-11-12 09:28 UTC
The method call for the constructor of :Student is missing. Should have at least a new Student() called.

![image.png](https://raw.githubusercontent.com/weidak/pe/main/files/89b5f148-b6d3-4469-8e56-25a9c6dfb463.png)

**Comment by nus-se-script** [comment] 2021-11-16 18:32
# Team's Response
Similar concept, with a different class.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># No command was called to construct the :ClassList
>
>In the same architecture sequence diagram on page 3, the command that calls the constructor of :ClassList is missing.
>
>Should at least have new ClassList()
>
>![image.png](https://raw.githubusercontent.com/nus-cs2113-AY2122S1/pe/master/files/eb0f1d29-5673-4548-ae3a-17e7e47c1e82.png)
>
>
>
>
>
>
><hr>
><sub>[original: nus-cs2113-AY2122S1/pe-interim#1768] [original labels: severity.Medium type.DocumentationBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>Format related. Does not hinder understanding that it is an object creation as it explicitly points to the classname instead of an activation bar.
>
>The textbook only states the object creation notations are:
>* The arrow that represents the constructor arrives at the side of the box representing the instance.
>* The activation bar represents the period the constructor is active.
>
>Reference: https://nus-cs2113-ay2122s1.github.io/website/se-book-adapted/chapters/uml.html#object-creation


# Items for the Tester to Verify
## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)





- [x] I disagree

**Reason for disagreement:** As they of different diagrams, I don't think they should be classified under the same bug as they are missing a different method call. As such, this could be the work of another person instead, and they should consider it as a separate bug.

-------------------
## :question: Issue response

Team chose [`response.Rejected`]





- [x] I disagree

**Reason for disagreement:** Thank you for including the reference link. As seen in the reference link:


![image.png](https://raw.githubusercontent.com/weidak/pe/main/files/d682101c-d4f4-4c9d-9803-14ca7ebe1389.png)

There are method calls to construct these objects. Speaking from a personal anecdote during tutorial lessons, my tutor also brought up that constructor methods were missing from my sequence diagram. Aligning with these teachings, I believe this should be considered a bug as they did not mention that the method call was supposed to be optional.

-------------------
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.Medium`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------

**Closed as completed** 2022-11-06 05:35 UTC
Labels: severity.Medium, type.DocumentationBug, status.Done
